### ISSUE TITLE
can't restore from pre-train model

### ISSUE THREAD

**Issue by hao522** [yiling-chen/view-finding-network#1]
DataLossError (see above for traceback): Unable to open table file ./model-spp-max/model-spp-max.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?

**Comment by yiling-chen** [comment]
Hi,
I guess you used the full path of the pre-trained model as input?
In your case, please try
# python vfn_eval.py --pooling max --snapshot snapshots/model-spp-max

**Comment by hao522** [comment]
thanks, I figured it out, used  the wrong path. :)

**Comment by yiling-chen** [comment]
I am glad that helped. :)
