### ISSUE TITLE
evaluation error: InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [9216,1000] rhs shape= [12544,1000]

### ISSUE THREAD

**Issue by longpeng2008** [yiling-chen/view-finding-network#3]
InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [9216,1000] rhs shape= [12544,1000]

**Comment by yiling-chen** [comment]
Can you more clearly describe the situation and how to reproduce it?

**Comment by yiling-chen** [comment]
@longpeng2008 Assuming the issue was resolved on your side. Close issue.

**Comment by lifengheng** [comment]
just change the argument '--spp' from false to true.
